FROM public.ecr.aws/lambda/python:3.12

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}/requirements-lambda.txt
COPY app ${LAMBDA_TASK_ROOT}/app

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements-lambda.txt

CMD ["app.aws.webhook.handler"]
